name: Node.js CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Use Node.js

        uses: actions/setup-node@v3

        with:

          node-version: '16.x'

      - run: npm config set legacy-peer-deps true

      - run: npm i install eris-fleet

      - run: npm start



































